# Generated by Django 3.2.14 on 2022-09-02 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount', models.CharField(max_length=100)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('proof', models.ImageField(upload_to='proofs/')),
                ('order_status', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MainApp.product')),
            ],
        ),
    ]
