# Generated by Django 3.2.14 on 2022-09-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_auto_20220905_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity_ordered',
            field=models.IntegerField(default=1),
        ),
    ]
