# Generated by Django 3.2.14 on 2022-09-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_auto_20220906_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity_ordered',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
