# Generated by Django 3.2.14 on 2022-09-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0015_cart_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
