# Generated by Django 3.2.14 on 2022-09-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0016_alter_cart_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='foot_size',
            field=models.IntegerField(choices=[(1, 'SMALL'), (2, 'MEDIUM'), (3, 'BIG')], default=2),
        ),
    ]
