# Generated by Django 3.2.14 on 2022-09-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0019_order_ship_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Order Received'), (1, 'Payment Received'), (2, 'Delivered')], default=0),
        ),
    ]
