# Generated by Django 3.2.14 on 2022-09-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0020_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='Upload your screenshot of your payment!', null=True),
        ),
    ]
