# Generated by Django 4.1.5 on 2023-01-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0022_auto_20220910_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='category/')),
                ('products', models.ManyToManyField(to='MainApp.product')),
            ],
        ),
    ]
