# Generated by Django 4.1.5 on 2023-01-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0024_product_image2_product_image3_product_image4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='default_image',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
