# Generated by Django 4.1.5 on 2023-01-23 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0025_rename_image_category_default_image_remove_cart_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('qty', models.IntegerField(default=1)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='products')),
                ('image2', models.ImageField(null=True, upload_to='products')),
                ('image3', models.ImageField(null=True, upload_to='products')),
                ('image4', models.ImageField(null=True, upload_to='products')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='default_image',
            new_name='image',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MainApp.category'),
        ),
    ]
