# Generated by Django 4.1.5 on 2023-01-23 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0026_product_remove_order_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.IntegerField(default=1)),
                ('shoe_size', models.IntegerField(default=42)),
                ('amount', models.IntegerField(default=0)),
                ('ship_address', models.CharField(max_length=100, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('proof', models.ImageField(upload_to='proofs/')),
                ('order_status', models.IntegerField(choices=[(0, 'Order Received'), (1, 'Payment Received'), (2, 'Delivered')], default=0)),
                ('comment', models.TextField(blank=True, default='Upload your screenshot of your payment!', null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('shoe_size', models.IntegerField(default=42)),
                ('amount', models.IntegerField(default=0, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.client')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.product')),
            ],
        ),
    ]
