# Generated by Django 4.1.5 on 2023-01-23 13:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0029_product_review_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='review',
            new_name='reviews',
        ),
    ]
